apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-and-test
spec:
  steps:
    - name: cleanup
      image: alpine:latest
      script: |
        rm -rf *
    - name: test
      image: python:3.9-slim
      script: |
        pip install -r requirements.txt
        nosetests -v
